add jest unit reporting

diff --git a/.github/workflows/test-prompts.yml b/.github/workflows/test-prompts.yml
--- a/.github/workflows/test-prompts.yml
+++ b/.github/workflows/test-prompts.yml
@@ -43,10 +43,18 @@ jobs:
         run: npm run build
 
       - name: Run tests
-        run: npm run test:prompts
+        run: npm run test:prompts -- --ci --reporters=default --reporters=jest-junit
         env:
           CHECKLY_API_KEY: ${{ secrets.CHECKLY_API_KEY }}
           CHECKLY_ACCOUNT_ID: ${{ secrets.CHECKLY_ACCOUNT_ID }}
           PROMETHEUS_INTEGRATION_KEY: ${{ secrets.PROMETHEUS_INTEGRATION_KEY }}
           CHECKLY_GITHUB_TOKEN: ${{ secrets.CHECKLY_GITHUB_TOKEN }}
           OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
+
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure() # run this step even if previous step failed
+        with:
+          name: Prompt Eval Tests # Name of the check run which will be created
+          path: reports/jest-*.xml # Path to test results
+          reporter: jest-junit # Format of test results
